2025-10-16 13:25:04 | INFO | üïí Scheduler iniciado ‚Äî executando jobs a cada 1h.
2025-10-16 13:25:04 | INFO | üöÄ Iniciando ciclo de atualiza√ß√£o...
2025-10-16 13:25:04 | INFO | ‚û°Ô∏è GET https://api.mercadolibre.com/users/me
2025-10-16 13:25:05 | INFO | üíæ CSV atualizado: data/processed\users_me.csv
2025-10-16 13:25:09 | INFO | Apps Script OK: 200 Upload OK
2025-10-16 13:25:09 | INFO | ‚û°Ô∏è GET https://api.mercadolibre.com/orders/search
2025-10-16 13:25:09 | ERROR | ‚ùå Erro 403 ao chamar https://api.mercadolibre.com/orders/search: {"message":"caller.id does not match buyer or seller","error":"caller.id.invalid","status":403,"cause":[]}
2025-10-16 13:25:09 | ERROR | ‚ùå Erro durante ciclo de atualiza√ß√£o: 403 Client Error: Forbidden for url: https://api.mercadolibre.com/orders/search?seller=731958
Traceback (most recent call last):
  File "C:\Users\ACER\meli_api_vanzak\src\scheduler.py", line 68, in run_all_jobs
    job_orders_recent(seller_id=ADVERTISER_ID)
  File "C:\Users\ACER\meli_api_vanzak\src\jobs.py", line 133, in job_orders_recent
    data = meli_get("/orders/search", params=params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ACER\meli_api_vanzak\src\meli_client.py", line 26, in meli_get
    resp.raise_for_status()
  File "C:\Users\ACER\AppData\Local\Programs\Python\Python311\Lib\site-packages\requests\models.py", line 1024, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://api.mercadolibre.com/orders/search?seller=731958
2025-10-16 13:25:09 | INFO | Adding job tentatively -- it will be properly scheduled when the scheduler starts
2025-10-16 13:25:09 | INFO | Added job "run_all_jobs" to job store "default"
2025-10-16 13:25:09 | INFO | Scheduler started
